language: cpp
compiler:
- clang
- gcc
before_install:
# pre build binary for the opencv version that i use, build from git@github.com:stalinizer/opencv.git
- wget https://www.dropbox.com/s/2stbngq02r84wfp/libcv-dev_2.5_amd64.deb
- sudo dpkg -i -y libcv-dev_2.5_amd64.deb
script:
- dpkg-buildpackage -b -uc -us

