# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/build/stalinizer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/build/stalinizer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/build/stalinizer/CMakeFiles /root/build/stalinizer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/build/stalinizer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named composetest

# Build rule for target.
composetest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 composetest
.PHONY : composetest

# fast build rule for target.
composetest/fast:
	$(MAKE) -f CMakeFiles/composetest.dir/build.make CMakeFiles/composetest.dir/build
.PHONY : composetest/fast

#=============================================================================
# Target rules for targets named stalinize.cgi

# Build rule for target.
stalinize.cgi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stalinize.cgi
.PHONY : stalinize.cgi

# fast build rule for target.
stalinize.cgi/fast:
	$(MAKE) -f CMakeFiles/stalinize.cgi.dir/build.make CMakeFiles/stalinize.cgi.dir/build
.PHONY : stalinize.cgi/fast

src/cgi/compose.o: src/cgi/compose.c.o
.PHONY : src/cgi/compose.o

# target to build an object file
src/cgi/compose.c.o:
	$(MAKE) -f CMakeFiles/composetest.dir/build.make CMakeFiles/composetest.dir/src/cgi/compose.c.o
.PHONY : src/cgi/compose.c.o

src/cgi/compose.i: src/cgi/compose.c.i
.PHONY : src/cgi/compose.i

# target to preprocess a source file
src/cgi/compose.c.i:
	$(MAKE) -f CMakeFiles/composetest.dir/build.make CMakeFiles/composetest.dir/src/cgi/compose.c.i
.PHONY : src/cgi/compose.c.i

src/cgi/compose.s: src/cgi/compose.c.s
.PHONY : src/cgi/compose.s

# target to generate assembly for a file
src/cgi/compose.c.s:
	$(MAKE) -f CMakeFiles/composetest.dir/build.make CMakeFiles/composetest.dir/src/cgi/compose.c.s
.PHONY : src/cgi/compose.c.s

src/cgi/stalinize.o: src/cgi/stalinize.c.o
.PHONY : src/cgi/stalinize.o

# target to build an object file
src/cgi/stalinize.c.o:
	$(MAKE) -f CMakeFiles/stalinize.cgi.dir/build.make CMakeFiles/stalinize.cgi.dir/src/cgi/stalinize.c.o
.PHONY : src/cgi/stalinize.c.o

src/cgi/stalinize.i: src/cgi/stalinize.c.i
.PHONY : src/cgi/stalinize.i

# target to preprocess a source file
src/cgi/stalinize.c.i:
	$(MAKE) -f CMakeFiles/stalinize.cgi.dir/build.make CMakeFiles/stalinize.cgi.dir/src/cgi/stalinize.c.i
.PHONY : src/cgi/stalinize.c.i

src/cgi/stalinize.s: src/cgi/stalinize.c.s
.PHONY : src/cgi/stalinize.s

# target to generate assembly for a file
src/cgi/stalinize.c.s:
	$(MAKE) -f CMakeFiles/stalinize.cgi.dir/build.make CMakeFiles/stalinize.cgi.dir/src/cgi/stalinize.c.s
.PHONY : src/cgi/stalinize.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... composetest"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... stalinize.cgi"
	@echo "... src/cgi/compose.o"
	@echo "... src/cgi/compose.i"
	@echo "... src/cgi/compose.s"
	@echo "... src/cgi/stalinize.o"
	@echo "... src/cgi/stalinize.i"
	@echo "... src/cgi/stalinize.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

